/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jamesfinalproject;

import library.Library;

/**
 *
 * @author James
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    public MainWindow() {
        
        initComponents();                                                       //Initializes the GUI's components
        
        welcomeText.setText("Welcome " + Library.username +"!");                //Sets the welcome text
        
        emailButton.setToolTipText("E-mail");                                   //These lines of code create the text boxes that appear over the buttons after the mouse hover over them
        ticTacToeButton.setToolTipText("Tic Tac Toe");                          //They display the name of each feature
        notepadButton.setToolTipText("Notepad");
        weatherButton.setToolTipText("Weather");
        calculatorButton.setToolTipText("Calculator");
        webButton.setToolTipText("Web browser");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        welcomeText = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        emailButton = new javax.swing.JButton();
        weatherButton = new javax.swing.JButton();
        calculatorButton = new javax.swing.JButton();
        notepadButton = new javax.swing.JButton();
        webButton = new javax.swing.JButton();
        ticTacToeButton = new javax.swing.JButton();
        logOutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("What would you like to do?");

        emailButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/emailIcon.png"))); // NOI18N
        emailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailButtonActionPerformed(evt);
            }
        });

        weatherButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/weatherIcon.png"))); // NOI18N
        weatherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weatherButtonActionPerformed(evt);
            }
        });

        calculatorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/calculatorIcon.png"))); // NOI18N
        calculatorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatorButtonActionPerformed(evt);
            }
        });

        notepadButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/notepadIcon.png"))); // NOI18N
        notepadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notepadButtonActionPerformed(evt);
            }
        });

        webButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/wikipediaIcon.png"))); // NOI18N
        webButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webButtonActionPerformed(evt);
            }
        });

        ticTacToeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/ticTacToeIcon.png"))); // NOI18N
        ticTacToeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticTacToeButtonActionPerformed(evt);
            }
        });

        logOutButton.setText("Log out");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(welcomeText)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logOutButton))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(notepadButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(emailButton))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(webButton)
                                    .addGap(18, 18, 18)
                                    .addComponent(ticTacToeButton))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(weatherButton)
                                    .addGap(18, 18, 18)
                                    .addComponent(calculatorButton))))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcomeText)
                    .addComponent(logOutButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(weatherButton)
                    .addComponent(calculatorButton)
                    .addComponent(emailButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(notepadButton)
                    .addComponent(webButton)
                    .addComponent(ticTacToeButton))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    
    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        // TODO add your handling code here:
        
        LoginWindow login = new LoginWindow();                                  //Creates a new login window
        login.setVisible(true);                                                 //Makes the login window visible
        login.setLocationRelativeTo(null);                                      //Positions it in the centre of the screen
        
        this.dispose();                                                         //Closes this window
        
    }//GEN-LAST:event_logOutButtonActionPerformed

  
    
    
    
    
    private void emailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailButtonActionPerformed
        // TODO add your handling code here:
        
        EmailWindow email = new EmailWindow();                                  //Creates a new e-mail window
        email.setVisible(true);                                                 //Makes the e-mail window visible
        email.setLocationRelativeTo(null);                                      //Positions it in the centre of the screen
        
    }//GEN-LAST:event_emailButtonActionPerformed

   
    
    
    
    
    private void weatherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weatherButtonActionPerformed
        // TODO add your handling code here:
        
        WeatherWindow weather = new WeatherWindow();                            //Creates a new weather window
        weather.setVisible(true);                                               //Makes the weather window visible
        weather.setLocationRelativeTo(null);                                    //Positions it in the centre of the screen
        
    }//GEN-LAST:event_weatherButtonActionPerformed


    
    
    
    
    private void calculatorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatorButtonActionPerformed
        // TODO add your handling code here:
        
        CalculatorWindow calculator = new CalculatorWindow();                   //Creates a new calculator window
        calculator.setVisible(true);                                            //Makes the calculator window visible
        calculator.setLocationRelativeTo(null);                                 //Positions it in the centre of the screen
        
    }//GEN-LAST:event_calculatorButtonActionPerformed

    
    
    
    
    
    private void notepadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notepadButtonActionPerformed
        // TODO add your handling code here:
        
        NotepadWindow notepad = new NotepadWindow();                            //Creates a new notepad window
        notepad.setVisible(true);                                               //Makes the notepad window visible
        notepad.setLocationRelativeTo(null);                                    //Positions it in the centre of the screen
        
    }//GEN-LAST:event_notepadButtonActionPerformed

 
    
    
    
    
    private void webButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webButtonActionPerformed
        // TODO add your handling code here:
        
        WebWindow browser = new WebWindow();                                    //Creates a new browser window
        browser.setVisible(true);                                               //Makes the browser window visible
        browser.setLocationRelativeTo(null);                                    //Positions it in the centre of the screen
        
    }//GEN-LAST:event_webButtonActionPerformed
  

    
    
    
    
    private void ticTacToeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticTacToeButtonActionPerformed
        // TODO add your handling code here:
        
        TicTacToeWindow ticTacToe = new TicTacToeWindow();                      //Creates a new tic tac toe window
        ticTacToe.setVisible(true);                                             //Makes the tic tac toe window visible
        ticTacToe.setLocationRelativeTo(null);                                  //Positions it in the centre of the screen
        
    }//GEN-LAST:event_ticTacToeButtonActionPerformed
    
    
    
    //Computer generated GUI variables
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculatorButton;
    private javax.swing.JButton emailButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logOutButton;
    private javax.swing.JButton notepadButton;
    private javax.swing.JButton ticTacToeButton;
    private javax.swing.JButton weatherButton;
    private javax.swing.JButton webButton;
    private javax.swing.JLabel welcomeText;
    // End of variables declaration//GEN-END:variables
}
