/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jamesfinalproject;

import java.awt.*;
import java.io.FileReader;
import java.io.IOException;
import java.net.*;
import library.Library;

/**
 *
 * @author James
 */
public class WebWindow extends javax.swing.JFrame {

    /**
     * Creates new form WikipediaWindow
     */
    public String fileName;                                                     //Creates a variable to store the file name
    public boolean newUser;                                                     //Tracks if the user is new or not
    public boolean validAddress = true;                                         //Tracks if the web address is valid

    public WebWindow() {
        
        initComponents();                                                       //Initializes the GUI components

        String tempString = "";                                                 //Creates a temporary string
        char[] usernameChars = Library.username.toCharArray();                  //Converts the username to a character array

        for (int i = 0; i < Library.username.length(); i++) {                   
            tempString = tempString + (int) usernameChars[i];                   //Converts each character in the area to its ascii value, and adds it unto the temporary string
        }

        fileName = tempString + "wb.txt";                                       //Creates the file name using the tempString and adding "wb.txt"

        try {
            FileReader file = new FileReader(fileName);                         //Creates a new file reader
            newUser = false;                                                    //If it works, the user must have already used this feature
        } catch (IOException e) {
            newUser = true;                                                     //If it doesn't, they are new
        }

        if (!newUser) {                                                         //If they are not a new user:
            
            String[] info = Library.read(fileName);                             //Reads the file
            Integer[] visits = new Integer[info.length / 2];                    //Creates an array to hold each websites' number of visits
            String[] sites = new String[info.length / 2];                       //Creates an array to hold each web address
            
            for (int i = 0; i < sites.length; i++) {                            //Organises the info into the correct arrays
                sites[i] = info[i * 2];
                visits[i] = Integer.valueOf(info[(i * 2) + 1]);
            }

            Object[][] toSort = {sites, visits};                                //Creates an object to sort
            toSort = Library.sortHighToLow(toSort, 1);                          //Sorts the data by number of visits
            
            for (Object object : toSort[0]) {
                websites.addItem(String.valueOf(object));                       //Display the sorted array of sites in the drop down menu
            }
            
        } else {                                                                //If they are new:
            
            String[] defaultSites = {"www.google.ca", "0", "https://en.wikipedia.org/wiki/Main_Page", "0", "http://techthings.ca/learn/index.htm", "0"}; //Creates the array of default info
            Library.write(fileName, defaultSites, false);                       //Writes the default info to the file
            
            for (int i = 0; i < defaultSites.length; i = i + 2) {
                websites.addItem(defaultSites[i]);                              //Adds the defaults to the drop down menu
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        websites = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        goButton = new javax.swing.JButton();
        newSite = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        errorText = new javax.swing.JLabel();
        buttonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Web Browser");

        jLabel3.setText("Website:");

        jLabel4.setText("New Website:");

        goButton.setText("Go");
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        addButton.setText("Add & Go");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        errorText.setForeground(new java.awt.Color(255, 0, 0));

        buttonBack.setText("Back");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(newSite))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(websites, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(goButton)
                            .addComponent(addButton)
                            .addComponent(buttonBack)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(errorText)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(websites, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goButton))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(newSite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton))
                .addGap(18, 18, 18)
                .addComponent(errorText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonBack)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
        // TODO add your handling code here:

        String site = String.valueOf(websites.getSelectedItem());               //Gets the site from the drop down menu

        String[] info = Library.read(fileName);                                 //Reads the file

        Integer[] visits = new Integer[info.length / 2];                        //Creates an array to hold each websites' number of visits
        String[] sites = new String[info.length / 2];                           //Creates an array to hold each web address

        for (int i = 0; i < sites.length; i++) {                                //Organises the info into the correct arrays
            sites[i] = info[i * 2];
            visits[i] = Integer.valueOf(info[(i * 2) + 1]);
        }

        for (int i = 0; i < sites.length; i++) {
            if (sites[i].equalsIgnoreCase(site)) {                              //Searches through the array of sites for the site selected
                visits[i]++;                                                    //Once found, increases its visits by one
            }
        }

        for (int i = 0; i < sites.length; i++) {                                //Combines the arrays back info one array
            info[i * 2] = sites[i];
            info[(i * 2) + 1] = String.valueOf(visits[i]);
        }

        Library.write(fileName, info, false);                                   //Writes the updated data to the file
        
        URI uri = URI.create(site);                                             //Creates a uri from the address
        openWebpage(uri);                                                       //Opens the uri
        
        this.dispose();                                                         //Closes this window

    }//GEN-LAST:event_goButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:

        String site = newSite.getText();                                        //Gets the site from the text field
        
        URI uri = URI.create(site);                                             //Creates a uri from the address
        openWebpage(uri);                                                       //Opens the uri
        
        if (validAddress == true) {                                             //If it worked:
            
            String[] newInfo = {site, "1"};                                     //Creates an array with the new info 
            Library.write(fileName, newInfo, true);                             //Writes it to the file
            
            this.dispose();
            
        } else {                                                                //If it didn't:
            
            errorText.setText("Invalid Web Address");                           //Displays the error message
            
        }

    }//GEN-LAST:event_addButtonActionPerformed

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        // TODO add your handling code here:

        this.dispose();                                                         //Closes this window

    }//GEN-LAST:event_buttonBackActionPerformed
        
        /**
         * This code is adapted from that of Vulcan, which can be found here:
         * https://stackoverflow.com/questions/10967451/open-a-link-in-browser-with-java-button
         * 
         * @param uri
         */
    
    public void openWebpage(URI uri) {
        Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
        if (desktop != null && desktop.isSupported(Desktop.Action.BROWSE)) {
            try {
                desktop.browse(uri);
            } catch (IOException e) {
                validAddress = false;
            }
        }
    }

    public void openWebpage(URL url) {
        try {
            openWebpage(url.toURI());
        } catch (URISyntaxException e) {
            validAddress = false;
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton buttonBack;
    private javax.swing.JLabel errorText;
    private javax.swing.JButton goButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField newSite;
    private javax.swing.JComboBox<String> websites;
    // End of variables declaration//GEN-END:variables
}
